apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ctfd.fullname" . }}-logs
spec:
  {{- if .Values.persistence.logs.storageClassName }}
  storageClassName: {{ .Values.persistence.logs.storageClassName }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.logs.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ctfd.fullname" . }}-uploads
spec:
  {{- if .Values.persistence.uploads.storageClassName }}
  storageClassName: {{ .Values.persistence.uploads.storageClassName }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.uploads.size }}
