replicaCount: 1

image:
  repository: ghcr.io/ctfd/ctfd
  pullPolicy: IfNotPresent
  tag: "3.7.7"

imagePullSecrets: []

nameOverride: ""

fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  fsGroup: 1001

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1001

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /healthcheck
    port: http
  initialDelaySeconds: 120

readinessProbe:
  httpGet:
    path: /healthcheck
    port: http
  initialDelaySeconds: 120

persistence:
  logs:
    size: 1Gi
    storageClassName: ""
  uploads:
    size: 1Gi
    storageClassName: ""
